wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part1.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part2.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part3.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part4.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part5.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part6.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part7.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part8.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part9.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part10.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part11.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part12.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part13.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part14.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part15.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part16.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part17.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part18.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part19.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part20.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part21.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part22.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part23.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part24.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part25.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_FE_part26.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part1.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part2.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part3.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part4.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part5.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part6.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part7.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part8.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part9.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part10.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part11.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part12.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part13.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part14.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part15.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part16.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part17.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part18.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part19.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part20.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part21.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part22.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part23.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part24.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part25.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part26.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part27.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part28.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part29.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part30.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part31.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part32.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part33.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part34.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part35.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part36.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part37.tar.gz --no-check-certificate
wget https://thor.robots.ox.ac.uk/HowTo100M/S3_whisperX_large_v2/video_nonFE_part38.tar.gz --no-check-certificate